forms.py
from wtforms import form, fields, validators, ValidationError
from wtforms.widgets.html5 import NumberInput
from flask import current_app as app


class GameForm(form.Form):
    OPTIONS = app.config['GAME_OPTIONS']
    MINIMUM = app.config['GAME_MINIMUM']
    MAXIMUM = app.config['GAME_MAXIMUM']

    modes = fields.RadioField(
        label='Modes',
        choices=[
            ("0", '{} x {} ({} mines)'.format(OPTIONS[0]['width'], OPTIONS[0]['height'], OPTIONS[0]['mines'])),
            ("1", '{} x {} ({} mines)'.format(OPTIONS[1]['width'], OPTIONS[1]['height'], OPTIONS[1]['mines'])),
            ("2", '{} x {} ({} mines)'.format(OPTIONS[2]['width'], OPTIONS[2]['height'], OPTIONS[2]['mines'])),
            ("3", 'Custom')
        ],
        default='0',
        validators=[validators.Required()]
    )

    width = fields.IntegerField(
        label='Width',
        default=MINIMUM['width'],
        validators=[validators.NumberRange(min=MINIMUM['width'], max=MAXIMUM['width'])],
        widget=NumberInput(min=MINIMUM['width'], max=MAXIMUM['width'])
    )

    height = fields.IntegerField(
        label='Height',
        default=MINIMUM['height'],
        validators=[validators.NumberRange(min=MINIMUM['height'], max=MAXIMUM['height'])],
        widget=NumberInput(min=MINIMUM['height'], max=MAXIMUM['height'])
    )

    mines = fields.IntegerField(
        label='Mines',
        default=MINIMUM['mines'],
        validators=[validators.NumberRange(min=MINIMUM['mines'], max=MAXIMUM['mines'])],
        widget=NumberInput(min=MINIMUM['mines'], max=MAXIMUM['mines'])
    )

app.py
from flask import Flask, render_template
from extensions import mongo, socket

app = Flask(__name__)

# configuration
app.config['SECRET_KEY'] = 'apw#%17fe39^&@.'
app.config['MONGO_HOST'] = 'localhost'
app.config['MONGO_PORT'] = 27017
app.config['MONGO_DBNAME'] = 'minesweeper'

app.config['GAME_MINIMUM'] = {'width': 10, 'height': 10, 'mines': 20}
app.config['GAME_MAXIMUM'] = {'width': 35, 'height': 15, 'mines': 100}
app.config['GAME_OPTIONS'] = [
    {'width': 10, 'height': 10, 'mines': 20},
    {'width': 18, 'height': 15, 'mines': 50},
    {'width': 25, 'height': 15, 'mines': 75}
]


with app.app_context():
    mongo.init_app(app)
    socket.init_app(app)

    from views import view
    app.register_blueprint(view)


@app.errorhandler(404)
def page_not_found(e):
    return render_template('404.html'), 404


if __name__ == '__main__':
    socket.run(app)

views.py
from flask import Blueprint, request, render_template, redirect, url_for, current_app as app, abort
from db_connector import DatabaseConnector as database
from game_factory import GameFactory
from game import Game
from forms import GameForm
from extensions import socket
from flask_socketio import emit, join_room, leave_room

view = Blueprint("view", __name__)

OPTIONS = app.config['GAME_OPTIONS']


@socket.on('join')
def join(id):
    join_room(id)

    game_json = database.get_game(id)

    if not game_json:
        abort(404)

    game = Game(game_json['data'])

    emit('game-data', game.to_json(is_view=True), room=id)


@socket.on('action')
def action(message):
    id = message['id']
    action = message['action']
    x = int(message['x'])
    y = int(message['y'])

    game_json = database.get_game(id)
    if not game_json:
        abort(404)

    game = Game(game_json['data'])

    if action == "click":
        game.open(x, y)
    if action == "right-click":
        game.flag(x, y)
    if action == "double-click":
        game.double_open(x, y)

    database.update_game(id, game.to_json())

    emit('game-data', game.to_json(is_view=True), room=id)


@socket.on('leave')
def leave(id):
    leave_room(id)


@view.route('/', methods=['GET', 'POST'])
def index():
    form = GameForm(request.form)

    if request.method == 'POST' and form.validate():
        # get user's choice
        mode = form.modes.data
        if mode == "3":
            width = form.width.data
            height = form.height.data
            mines = form.mines.data
        else:
            width = OPTIONS[int(mode)]['width']
            height = OPTIONS[int(mode)]['height']
            mines = OPTIONS[int(mode)]['mines']

        # generate game and save to database
        game = GameFactory.generate_new_game(width, height, mines)

        id = database.insert_game(game.to_json())

        return redirect(url_for('view.game', id=id))

    return render_template('index.html', form=form)


@view.route('/game/<id>', methods=['GET'])
def game(id):
    game_data = database.get_game(id)
    if not game_data:
        abort(404)

    return render_template('game.html', id=id)

templates/_layout.html
<!DOCTYPE html>
<html lang="en">

<head>
	<title>Minesweeper</title>
	<meta charset="utf-8" />

	<link rel="shortcut icon" href="{{ url_for('static', filename='images/bomb.png') }}" type="image/x-icon">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">

	<script type="text/javascript" src="{{ url_for('static', filename='js/jquery-3.2.1.min.js') }}"></script>
    <script src="https://use.fontawesome.com/9098b54716.js"></script>
</head>

<body>
	<div>
	   {% block content %}
	   {% endblock %}
	</div>
</body>

</html>

templates/game.html
{% extends "_layout.html" %}

{% block content %}

    <script type="text/javascript" src="{{ url_for('static', filename='js/game.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/socket.io-1.3.6.min.js') }}"></script>

    <div class="container">
         <div id="game-title">
             <i class="fa fa-bomb"></i> Minesweeper <label>by Giang Vu</label>
         </div>

        <div id="top">
            <div class="flags">
                <label id="flags"></label>
                <div class="flag"></div>
            </div>

            <div id="status"></div>

        </div>

        <input type="hidden" id="id" value="{{ id }}">
        <div id="board"></div>

        <div id="bottom">
            <button id="new" title="New Game" onclick="newGame()">
                <i class="fa fa-play"></i> New Game
            </button>
            <button id="copy" title="Copy Url" onclick="copyUrl()">
                <i class="fa fa-link"></i> Copy Url
            </button>
        </div>
    </div>
{% endblock %}

templates/index.html
{% extends "_layout.html" %}

{% macro render_field_with_errors(field) %}
    <div>
        {{ field.label }} {{ field(**kwargs)|safe }}
        {% if field.errors %}
          <ul>
          {% for error in field.errors %}
            <li>{{ error }}</li>
          {% endfor %}
          </ul>
        {% endif %}
    </div>
{% endmacro %}

{% block content %}
     <script src="{{ url_for('static', filename='js/index.js') }}"></script>


    <div id="form">
        <div id="title">
            <i class="fa fa-bomb"></i>
            Minesweeper <label>Multiplayer</label>
        </div>
        <p id="info">
            Access the same game URL to play together
        </p>
        <form action="{{ url_for('view.index') }}" method="POST">
            {{ form.csrf_token }}
            <div id="option">
             {% for mode in form.modes %}
                <div>{{ mode(class="game-option") }}
                    {{ mode.label }}
                </div>
             {% endfor %}

            <div id="custom-option">
                {{ render_field_with_errors(form.width) }}
                {{ render_field_with_errors(form.height) }}
                {{ render_field_with_errors(form.mines) }}
            </div>
            </div>
            <div id="start-container">
                <button id="start" title="New Game" type="submit">
                    <i class="fa fa-play"></i> New Game
                </button>
            </div>
        </form>
    </div>

{% endblock %}